# double_pinyin.custom.yaml
#
# è£œéªåŠŸèƒ½ï¼šå°‡è‡ªç„¶ç¢¼é›™æ‹¼çš„è©åº«ä¿®æ”¹çˆ²æœ™æœˆæ‹¼éŸ³æ“´å……è©åº«
#
# ä½œè€…ï¼šç‘¾æ˜€ <cokunhui@gmail.com>
#
# éƒ¨ç½²ä½ç½®ï¼š
# ~/.config/ibus/rime  (Linux)
# ~/Library/Rime  (Mac OS)
# %APPDATA%\Rime  (Windows)
#
# æ–¼é‡æ–°éƒ¨ç½²å¾Œç”Ÿæ•ˆ
#
#
# æ³¨æ„ï¼šæœ¬è£œéªé©ç”¨æ–¼æ‰€æœ‰é›™æ‹¼æ–¹æ¡ˆï¼ˆã€Œè‡ªç„¶ç¢¼é›™æ‹¼ã€ã€ã€Œæ™ºèƒ½ABCé›™æ‹¼ã€ã€ã€Œå°é¶´é›™æ‹¼ã€ã€ã€ŒMSPYé›™æ‹¼ã€ï¼‰ã€‚
# åªé ˆå°‡æœ¬ custom.yaml çš„å‰é¢åå­—æ”¹çˆ²å°æ‡‰çš„è¼¸å…¥æ–¹æ¡ˆåå­—ç„¶å¾Œæ”¾å…¥ç”¨æˆ¶æ–‡ä»¶å¤¾é‡æ–°éƒ¨ç½²å³å¯ã€‚å¦‚ double_pinyin_abc.custom.yamlã€‚
# æœ™æœˆæ‹¼éŸ³ç”¨æˆ¶è«‹ä½¿ç”¨ luna_pinyin.custom.yamlã€‚
#
#
# é™„é›™æ‹¼æ–¹æ¡ˆèˆ‡å…¶å°æ‡‰çš„ id ä¸€è¦½è¡¨ï¼š
# è¼¸å…¥æ–¹æ¡ˆ	id
# è‡ªç„¶ç¢¼é›™æ‹¼	double_pinyin
# æ™ºèƒ½ABCé›™æ‹¼	double_pinyin_abc
# å°é¶´é›™æ‹¼	double_pinyin_flypy
# MSPYé›™æ‹¼	double_pinyin_mspy
#

patch:
  # è¼‰å…¥æœ™æœˆæ‹¼éŸ³æ“´å……è©åº«
  "translator/dictionary": luna_pinyin.extended
  engine/+:
    translators/+:
      - lua_translator@time_translator
      - lua_translator@date_translator
      - lua_translator@week_translator
      - lua_translator@lunar_translator
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "ğŸˆšï¸", "ğŸˆ¶ï¸" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: none
    inherit_comment: false
__patch:
# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin_flypy {
  - patch/+:
      __include: easy_en:/patch
# }
